dvc_ids:
  - 977050757461336124  # 創建動態語音 頻道ID
  # - ...  # 可多個，以此類推
member_role_id: 1067114343868661760  # @組織成員 身份組ID
apply_channel_id: 1056482755602563082  # 面試室 頻道ID
meeting_category_id: 1056483155097432136  # 面試室 類別ID
job_role:  # '工作名稱': 該工作的身份組ID
  '平台開發部 - UI/UX組 - 使用者介面設計': 
  '平台開發部 - UI/UX組 - 使用者體驗': 
  '平台開發部 - 前端組 - 開發工程師 (Vue.js/TS)': 
  '平台開發部 - 後端組 - 開發工程師 (Express.js/TS)': 
  '平台開發部 - 應用程式組 - 開發工程師 (Flutter)': 
  'Discord Bot 開發部 - 開發工程師 (Python)': 1067114419479400509
  '行政部 - 企劃組 - 企劃人員': 
  '行政部 - 人事組 - 人事人員': 
  '行政部 - 宣傳組 - 海報與文宣設計': 
  '行政部 - 宣傳組 - 影音':  
  '行政部 - 宣傳組 - 社群管理': 
  # ...  # 若以後有更多職位，以上方格式類推
team_role:  # '部門名稱': 該部門的身份組ID
  '平台開發部': 
  'Discord Bot 開發部': 1067114535032463440
  '行政部': 
  # ...  # 若以後有更多組別，以上方格式類推
hr_role_id: 1067114618494922802  # @人事 身份組ID
